name: Maven test and build using docker-compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Startup database using docker compose
      run: docker-compose -f docker-compose-environment.yml up -d
    - name: Build with Maven and run tests
      run: mvn -B package --file pom.xml
    - name: shutdown database using docker compose
      run: docker-compose -f docker-compose-environment.yml down
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: "**/*.jar"

